version: "3.8"


services:
  postgres:
    image: postgres:15
    container_name: pgdb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome@123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./monolithic-sample/db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: ./monolithic-sample
    container_name: erp_monolithic_service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=employee_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Welcome@123
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
